config/routes.rb
Rails.application.routes.draw do
  
  resources :project_types
  resources :services
  resources :service_types
  resources :work_diaries
  resources :purchase_items
  resources :purchases
  resources :materials
  resources :material_categories
  resources :bank_accounts
  resources :providers
  resources :banks
  resources :tasks
  resources :task_types
  resources :stages
  
  resources :constructions do
    resources :tasks
    resources :work_diaries
  end 

  resources :construction_types
  resources :taxes
  resources :deductions
  resources :benefits
  resources :benefit_types
  resources :employments
  resources :document_types
  
  resources :people do
    resources :employments    
  end
  
  resources :analyzes 
  resources :cities
  resources :countries
  resources :menu_items
  resources :phone_types
  resources :occupations
  resources :settings
  resources :states
  resources :users
  resources :workplaces
  
  devise_for :users, path: 'u'

  post 'utils/postal_code'
  post 'utils/cities'
  get 'utils/cities'

  root 'constructions#index'
  mount Crono::Web, at: '/crono'
end

app/models/employment.rb
class Employment < ApplicationRecord

  enum status: {
        active: 0,
        cancelled: 1        
  }  

  monetize :base_salary_cents

  belongs_to :occupation
  belongs_to :person

  has_many :benefits, dependent: :destroy
  accepts_nested_attributes_for :benefits, allow_destroy: true

  has_many :tasks
  has_many :frequencies

  has_and_belongs_to_many :constructions


  after_create :set_active_employment

  def set_active_employment
    self.person.employments.each do |emp|
      Employment.find(emp.id).update(status: 'cancelled')     
    end 
    self.status = 'active'
    self.save
  end  

  def total_benefits
    self.benefits.sum(:value_cents)
  end

  def full_description
    "#{self.person.name} (CPF: #{self.person.cpf} - Vínculo: #{self.occupation.name})" 
  end
  
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  load_and_authorize_resource
  # GET /employments
  
  def index
    @q = Employment.ransack(params[:q])
    @employments = @q.result(distinct: true).page(params[:page])
  end

  # GET /employments/1
  def show
    get_person
  end

  # GET /employments/new
  def new
    get_person
    @employment= @person.employments.build 
  end

  # GET /employments/1/edit
  def edit
  end

  # POST /employments
  def create
    get_person
    @employment = @person.employments.build(employment_params)  
    if @employment.save
      redirect_to @person, notice: 'Employment was successfully created.'      
    else
      render :new
    end
  end

  # PATCH/PUT /employments/1
  def update
    if @employment.update(employment_params)
      redirect_to @employment.person, notice: 'Employment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /employments/1
  def destroy
    @employment.destroy
    redirect_to employments_url, notice: 'Employment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment
      @employment = Employment.find(params[:id])
    end

    def get_person
      @person = Person.find(params[:person_id])
    end 

    # Only allow a trusted parameter "white list" through.
    def employment_params
      params.require(:employment).permit(:admission_date, :resignation_date, :base_salary, :occupation_id, :person_id,
        benefits_attributes: [
          :id, :_destroy, :benefit_type_id, :value
        ]
      )
    end
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/views/employments/_benefit_fields.html.erb
<div class="benefit nested-fields">
  <div class='row'>    
    <%= f.association :benefit_type, collection: BenefitType.order(:name), wrapper_html: { class: 'col-md-3' }  %>
    <%= f.input :value, wrapper_html: { class: 'col-md-3' } %>    

    <div class="col-md-2">
      <%= link_to_remove_association f, class: 'btn btn-danger top-32' do %>
        <i class="fa fa-fw fa-times"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/employments/_form.html.erb
<%= simple_form_for([@person, @employment]) do |f| %>
  <div class="card card-outline card-info">
    <div class="card-header">
      <h3 class="card-title">
        Dados do <%= object.class.model_name.human %> 
        <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default btn-xs" %>
        <%= f.submit 'Salvar', class: "btn btn-info btn-xs" %>
      </h3>
    </div>

    <div class="card-body">
      <div class="row">          
        <%= f.association :occupation, wrapper_html: { class: 'col-md-12' } %> 
        <%= f.input :admission_date,  html5: true,  wrapper_html: { class: 'col-md-3' } %>  
        <%= f.input :base_salary, wrapper_html: { class: 'col-md-3' } %>          
      </div>
    </div>  
  </div>


  <div class="tab-pane" id="tab_6">
  <div class="card card-outline card-info">
    <div class="card-header">
      <h3 class="card-title">
        Benefícios
      </h3>
    </div>
    <div class="card-body">
      <div id="documents" class='row'>
        <div class="col-md-12">
          <%= f.simple_fields_for :benefits do |be| %>
            <%= render 'benefit_fields', f: be %>
          <% end %>

          <div class="control-group">
            <div class="controls">
              <%= link_to_add_association f, :benefits do %>
                <div class="btn btn-success">
                  <i class="fa fa-fw fa-plus"></i> Adicionar Benefício
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




  <div class="card card-outline card-info">
    <div class="card-footer">
      <%= link_to 'Cancelar', @employment.person, class: "btn btn-default" %>
      <%= f.submit class: "btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/employments/edit.html.erb
<div class="card card-outline card-info">
  <div class="card-header">
    <h3 class="card-title">
      Profissional
    </h3>
  </div>
  <div class="table">
    <div id="plans" class='row'>
      <div class="card-body">  
      <table class="table table-bordered table-striped no-padding datatables">
        <thead>
          <tr>
            <th width="15%">Nome</th>
            <th>CPF</th>
          </tr>
        </thead>
        <tbody>
        
          <tr>     
              <td><%= @employment.person.name %> </td>  
              <td><%= @employment.person.cpf  %></td> 
                     
          </tr>
        
        </tbody>
      </table>          
      </div>
    </div>
  </div>
</div>


<%= render 'form', box_class: 'info', object: @employment %>

app/views/employments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employments</h1>

<table>
  <thead>
    <tr>
      <th>Admission date</th>
      <th>Resignation date</th>
      <th>Base salary</th>
      <th>Occupation</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employments.each do |employment| %>
      <tr>
        <td><%= employment.admission_date %></td>
        <td><%= employment.resignation_date %></td>
        <td><%= employment.base_salary %></td>
        <td><%= employment.place_id %></td>
        <td><%= employment.person_id %></td>
        <td><%= link_to 'Show', employment %></td>
        <td><%= link_to 'Edit', edit_employment_path(employment) %></td>
        <td><%= link_to 'Destroy', employment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employment', new_employment_path %>

app/views/employments/new.html.erb
<%= render 'form', box_class: 'info', object: @employment %>

app/views/employments/show.html.erb
<%= render 'shared/show', box_class: 'info', object: @employment %>

<div class="card card-outline card-info">
  <div class="card-header">
    <h3 class="card-title">
      Benefícios
    </h3>
  </div>
  <div class="table">
    <div id="beneficios" class='row'>
      <div class="card-body">  
      <table class="table table-bordered table-striped no-padding datatables">
        <thead>
          <tr>
            <th width="15%">Tipo de Benefício</th>
            <th>Valor</th>
          </tr>
        </thead>
        <tbody>
        <% @employment.benefits.each do |d| %>
          <tr>     
              <td><%= d.benefit_type.name %> </td>  
              <td><%= d.value %> </td>  
          </tr>
        <% end %>
        </tbody>
      </table>          
      </div>
    </div>
  </div>
</div>  


<div class="card card-outline card-info">
  <div class="card-header">
    <h3 class="card-title">
      Construções
    </h3>
  </div>
  <div class="table">
    <div id="beneficios" class='row'>
      <div class="card-body">  
      <table class="table table-bordered table-striped no-padding datatables">
        <thead>
          <tr>
            <th width="15%">Local de Trabalho</th>
            <th>Tipo de Construção</th>
            <th>Área (m²)</th>
            <th>Data de Início</th>
            <th>Data de Término</th>
          </tr>
        </thead>
        <tbody>
        <% @employment.constructions.each do |c| %>
          <tr>     
              <td><%= c.workplace.name %> </td>  
              <td><%= c.construction_type.name %> </td> 
              <td><%= c.area %> </td>
              <td><%= c.start_date %> </td>
              <td><%= c.end_date %> </td>   
          </tr>
        <% end %>
        </tbody>
      </table>          
      </div>
    </div>
  </div>
</div>  




<div class="card card-outline card-info">
  <div class="card-header">
    <h3 class="card-title">
      Tarefas  
    </h3>
  </div>
  

  <div class="card-body p-0">  
    <table class="bootstrap-table-mobile">
      <thead>
        <tr>
          <th data-align='center'>ID</th>
          <th data-align='center'>Etapa</th> 
          <th data-align='center'>Tipo de Tarefa</th>
          <th data-align='center'>Data de Início</th>
          <th data-align='center'>Data de Fim</th>
          <th data-align='center'>Orçamento Previsto</th>
          <th data-align='center'>Custo Real</th>
          <th data-align='center'>Status</th>
          <th data-align='center'>Ações</th>

        </tr>
      </thead>
      <tbody>
        <% @employment.tasks.each do |t| %>
          <tr>     
            <td> 
                <%= link_to construction_task_path(t.construction) do %>
                  <%= t.id %></i> 
                <% end %>    
            </td>    
           
            <td><%= t.task_type.stage.name %></td>
            <td><%= t.task_type.name %></td>
            <td><%= t.start_date %></td>  
            <td><%= t.end_date %></td>  
            <td><%= t.budget_amount %></td>
            <td><%= t.cost %></td>
            <td><%= t.status %></td>
            <td> 
              <%= link_to construction_task_path(t.construction), class: "btn btn-xs btn-info" do %>
                Visualizar </i> 
              <% end %>    
            </td>    
          </tr>
        <% end %>
      </tbody>
    </table>          
  </div>
</div> 