config/routes.rb
Rails.application.routes.draw do
  
  resources :project_types
  resources :services
  resources :service_types
  resources :work_diaries
  resources :purchase_items
  resources :purchases
  resources :materials
  resources :material_categories
  resources :bank_accounts
  resources :providers
  resources :banks
  resources :tasks
  resources :task_types
  resources :stages
  
  resources :constructions do
    resources :tasks
    resources :work_diaries
  end 

  resources :construction_types
  resources :taxes
  resources :deductions
  resources :benefits
  resources :benefit_types
  resources :employments
  resources :document_types
  
  resources :people do
    resources :employments    
  end
  
  resources :analyzes 
  resources :cities
  resources :countries
  resources :menu_items
  resources :phone_types
  resources :occupations
  resources :settings
  resources :states
  resources :users
  resources :workplaces
  
  devise_for :users, path: 'u'

  post 'utils/postal_code'
  post 'utils/cities'
  get 'utils/cities'

  root 'constructions#index'
  mount Crono::Web, at: '/crono'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
        can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  belongs_to :addressable, polymorphic: true
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  belongs_to :benefit_type
  belongs_to :employment

  monetize :value_cents
  
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_type
  #belongs_to :person

  belongs_to :documentable, polymorphic: true

  has_one_attached :attachment

end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :material_category

  def full_description
    "Categoria: #{self.material_category.name} - Material: #{self.name})" 
  end

end

app/models/person.rb
class Person < ApplicationRecord
  has_ancestry

  has_one_attached :photo
  has_one :account

   # para cadastro dos dependentes nested
   belongs_to :person, inverse_of: :people, optional: true
   has_many :people, inverse_of: :person, dependent: :destroy
   accepts_nested_attributes_for :people, allow_destroy: true
   

  belongs_to :user, optional: true
  belongs_to :city
  belongs_to :place, optional: true
  #belongs_to :county, class_name: "City", foreign_key: "county_id", optional: true
  
  has_many :addresses, dependent: :destroy, as: :addressable
  has_many :phones, dependent: :destroy, as: :phonable
  
  has_many :documents, dependent: :destroy, as: :documentable
  accepts_nested_attributes_for :documents
  

  has_many :employments, dependent: :destroy
  accepts_nested_attributes_for :employments, allow_destroy: true

  accepts_nested_attributes_for :user, allow_destroy: true
  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true

  validates :cpf, cpf: true
  validates :name, :rg, :birth, presence: true
  #validates :registration, :admission, :business_email, :place, presence: { unless: :person }
  validates :user, presence: { unless: :person }
 

  # para jogar dependentes no ancestry
  #before_save :set_parent_id
  


  def full_description
    "#{name} (CPF: #{cpf} )" 
  end


  def age
    now = Time.now.utc.to_date
    now.year - self.birth.year - (self.birth.to_date.change(:year => now.year) > now ? 1 : 0)
  end

 
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :phone_type
  belongs_to :phonable, polymorphic: true
end
    

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :work_diary
  
  has_one_attached :image, dependent: :destroy
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :work_diary
end

app/models/project.rb
class Project < ApplicationRecord

  enum status: {
    initiated: 0,
    finished: 1        
  }  

  enum advice: {
    cau: 0,
    crea: 1        
  }  

  belongs_to :project_type
  belongs_to :state
  belongs_to :employment
  belongs_to :construction

  has_one_attached :attachment
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :service_type
  belongs_to :provider
  belongs_to :task_type
  belongs_to :construction

   
  monetize :total_price_cents
end

app/models/setting.rb
class Setting < ApplicationRecord
    monetize :fee_with_service_cents
    monetize :fee_without_service_cents
end

app/models/stage.rb
class Stage < ApplicationRecord
    has_many :task_types, dependent: :destroy
    accepts_nested_attributes_for :task_types, allow_destroy: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country

  def name_with_state
    "#{name} - #{state&.acronym}"
  end
  
end

app/models/task.rb
class Task < ApplicationRecord

  enum status: {
    registered: 0,
    initiated: 1     
  } 

  belongs_to :task_type
  belongs_to :construction
  belongs_to :employment, optional: true

  monetize :budget_amount_cents
  monetize :cost_cents
  
end

app/models/tax.rb
class Tax < ApplicationRecord
    has_many :tax_ranges, dependent: :destroy
    accepts_nested_attributes_for :tax_ranges, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_one :person
end

app/models/wheater.rb
class Wheater < ApplicationRecord
    enum climate_condition: {
        sunny: 0,
        rainy: 1,
        storm: 2,
        cloudy: 3     
      } 

      enum shift: {
            morning: 0,
            evening: 1,
            night:2     
        } 

    belongs_to :work_diary  
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  load_and_authorize_resource

  # GET /stages
  def index
    @q = Stage.ransack(params[:q])
    @stages = @q.result(distinct: true).page(params[:page]).order('id ASC')
    
  end

  # GET /stages/1
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  def create
    @stage = Stage.new(stage_params)

    if @stage.save
      redirect_to @stage, notice: 'Stage was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stages/1
  def update
    if @stage.update(stage_params)
      redirect_to @stage, notice: 'Stage was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stages/1
  def destroy
    @stage.destroy
    redirect_to stages_url, notice: 'Stage was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def stage_params
      params.require(:stage).permit(:name,
        task_types_attributes: [
              :id, :name, :_destroy
        ])
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= simple_form_for(@stage) do |f| %>
  <div class="card card-outline card-info">
    <div class="card-header">
      <h3 class="card-title">
        Dados do <%= object.class.model_name.human %> 
        <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default btn-xs" %>
        <%= f.submit 'Salvar', class: "btn btn-info btn-xs" %>
      </h3>
    </div>

    <div class="card-body">
      <div class="row">          
        <%= f.input :name, wrapper_html: { class: 'col-md-8' } %>
      </div>
    </div>  
  </div>


  <div class="tab-pane" id="tab_5">
      <div class="card card-outline card-info">
        <div class="card-header">
          <h3 class="card-title">
            Tipos de Tarefa
          </h3>
        </div>
        <div class="card-body">
                    
          <div id="task_types" class='row'>
            <div class="col-md-12">
              <%= f.simple_fields_for :task_types do |tt| %>
                <%= render 'task_type_fields', f: tt %>
              <% end %>

              <div class="control-group">
                <div class="controls">
                  <%= link_to_add_association f, :task_types do %>
                    <div class="btn btn-success">
                      <i class="fa fa-fw fa-plus"></i> Adicionar Tipo de Tarefa
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>




  <div class="card card-outline card-info">
    <div class="card-footer">
      <%= f.submit class: "btn btn-info" %>
      <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/stages/_task_type_fields.html.erb
<div class="task_type nested-fields">
  <div class='row'>
    <%= f.input :name, wrapper_html: { class: 'col-md-5' }%> 
   
    <div class="col-md-2">
      <%= link_to_remove_association f, class: 'btn btn-danger top-32' do %>
        <i class="fa fa-fw fa-times"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/stages/edit.html.erb
<%= render 'form', object: @stage %>

app/views/stages/index.html.erb
<%= render 'shared/card_list',
  list: @stages,
  order: 'id',
  sort_all: true,
  show_new: true,
  card_class: 'info',
  table_class: 'bootstrap-table-mobile',
  show_columns: [
    'id',
    'name'
  ]
%>

app/views/stages/new.html.erb
<%= render 'form', object: @stage %>

app/views/stages/show.html.erb
<%= render 'shared/show', box_class: 'info', object: @stage%>


<div class="card card-outline card-info">
  <div class="card-header">
    <h3 class="card-title">
     Tipos de Tarefa 
    </h3>
  </div>
  

  <div class="card-body p-0">  
    <table class="bootstrap-table-mobile">
      <thead>
        <tr>
          <th data-align='center'>ID</th>
          <th data-align='left'>Nome</th> 
          <th data-align='center'>Ações</th>

        </tr>
      </thead>
      <tbody>
        <% @stage.task_types.each do |t| %>
          <tr>     
            <td> 
                <%= link_to task_type_path(t) do %>
                  <%= t.id %></i> 
                <% end %>    
            </td>    
           
            <td><%= t.name %></td>
            
            <td> 
              <%= link_to task_type_path(t), class: "btn btn-xs btn-info" do %>
                Visualizar </i> 
              <% end %>    
            </td>    
          </tr>
        <% end %>
      </tbody>
    </table>          
  </div>
</div> 